/**
 * SDRangel
 * This is the web REST/JSON API of SDRangel SDR software. SDRangel is an Open Source Qt5/OpenGL 3.0+ (4.3+ in Windows) GUI and server Software Defined Radio and signal analyzer in software. It supports Airspy, BladeRF, HackRF, LimeSDR, PlutoSDR, RTL-SDR, SDRplay RSP1 and FunCube    ---   Limitations and specifcities:    * In SDRangel GUI the first Rx device set cannot be deleted. Conversely the server starts with no device sets and its number of device sets can be reduced to zero by as many calls as necessary to /sdrangel/deviceset with DELETE method.   * Preset import and export from/to file is a server only feature.   * Device set focus is a GUI only feature.   * The following channels are not implemented (status 501 is returned): ATV and DATV demodulators, Channel Analyzer NG, LoRa demodulator   * The device settings and report structures contains only the sub-structure corresponding to the device type. The DeviceSettings and DeviceReport structures documented here shows all of them but only one will be or should be present at a time   * The channel settings and report structures contains only the sub-structure corresponding to the channel type. The ChannelSettings and ChannelReport structures documented here shows all of them but only one will be or should be present at a time    --- 
 *
 * OpenAPI spec version: 7.0.0
 * Contact: f4exb06@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "SWGFreqScannerActions.h"
#include "SWGHelpers.h"
#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace SWGSDRangel {

SWGFreqScannerActions::SWGFreqScannerActions(QString* json) {
    init();
    this->fromJson(*json);
}

SWGFreqScannerActions::SWGFreqScannerActions() {
    run = 0;
    m_run_isSet = false;
    clear_hits = 0;
    m_clear_hits_isSet = false;
}

SWGFreqScannerActions::~SWGFreqScannerActions() {
    this->cleanup();
}

void
SWGFreqScannerActions::init() {
    run = 0;
    m_run_isSet = false;
    clear_hits = 0;
    m_clear_hits_isSet = false;
}

void
SWGFreqScannerActions::cleanup() {
}

SWGFreqScannerActions*
SWGFreqScannerActions::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGFreqScannerActions::fromJsonObject(QJsonObject &pJson) {
    if (pJson.contains("run")) {
        ::SWGSDRangel::setValue(&run, pJson["run"], "qint32", "");
        this->m_run_isSet = true;
    }

    if (pJson.contains("clearHits")) {
        ::SWGSDRangel::setValue(&clear_hits, pJson["clearHits"], "qint32", "");
        this->m_clear_hits_isSet = true;
    }
}

QString
SWGFreqScannerActions::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    delete obj;
    return QString(bytes);
}

QJsonObject*
SWGFreqScannerActions::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    if(m_run_isSet){
        obj->insert("run", QJsonValue(run));
    }
    if(m_clear_hits_isSet){
        obj->insert("clearHits", QJsonValue(clear_hits));
    }
    return obj;
}

qint32
SWGFreqScannerActions::getRun() {
    return run;
}
void
SWGFreqScannerActions::setRun(qint32 run) {
    this->run = run;
    this->m_run_isSet = true;
}

qint32
SWGFreqScannerActions::getClearHits() {
    return clear_hits;
}
void
SWGFreqScannerActions::setClearHits(qint32 clear_hits) {
    this->clear_hits = clear_hits;
    this->m_clear_hits_isSet = true;
}

bool
SWGFreqScannerActions::isSet(){
    bool isObjectUpdated = false;
    do{
        if(m_run_isSet){
            isObjectUpdated = true; break;
        }
        if(m_clear_hits_isSet){
            isObjectUpdated = true; break;
        }
    }while(false);
    return isObjectUpdated;
}

bool
SWGFreqScannerActions::runIsSet() {
    return m_run_isSet;
}

bool
SWGFreqScannerActions::clearHitsIsSet() {
    return m_clear_hits_isSet;
}

}